default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5
  username:
  password:

development:
  <<: *default
  database: user-interviews-interview-dev

test:
  <<: *default
  database: user-interviews-interview-test

production:
  <<: *default
  database: user-interviews-interview-prod
